-- Secuencia automática (Genera valores automáticos para un campo)

-- Crear secuencia en la tabla (No permite inserción manual)
CREATE TABLE nombre_tabla (			
	campo		TIPODEDATO_ENTERO GENERATED AS IDENTITY
);

-- Crear secuencia en la tabla (No permite inserción manual)
CREATE TABLE nombre_tabla (			
	campo		TIPODEDATO_ENTERO GENERATED ALWAYS AS IDENTITY
);

-- Crear secuencia en la tabla (Permite inserción manual sin NULL)
CREATE TABLE nombre_tabla (			
	campo		TIPODEDATO_ENTERO GENERATED BY DEFAULT AS IDENTITY
);

-- Crear secuencia en la tabla (Permite inserción manual con NULL)
CREATE TABLE nombre_tabla (			
	campo		TIPODEDATO_ENTERO GENERATED BY DEFAULT ON NULL AS IDENTITY
);

-- Crear secuencia en la tabla con valor incial
CREATE TABLE nombre_tabla (			
	campo		TIPODEDATO_ENTERO GENERATED AS IDENTITY (START WITH valor_inicial)
);

-- Crear secuencia en la tabla con valor de incremento
CREATE TABLE nombre_tabla (			
	campo		TIPODEDATO_ENTERO GENERATED AS IDENTITY (INCREMENT BY valor_de_incremento)
);

-- Crear secuencia en la tabla con valor inicial y valor de incremento
CREATE TABLE nombre_tabla (			
	campo		TIPODEDATO_ENTERO GENERATED AS IDENTITY (START WITH valor_inicial INCREMENT BY valor_de_incremento)
);

-- Crear secuencia fuera de la tabla
NO SOPORTADO POR ORACLE

-- Cambiar valor actual del contador de secuencia
ALTER TABLE nombre_tabla MODIFY (campo TIPODEDATO_ENTERO GENERATED AS IDENTITY (START WITH valor_inicial));

-- Cambiar valor actual del incremento
ALTER TABLE nombre_tabla MODIFY (campo TIPODEDATO_ENTERO GENERATED AS IDENTITY (INCREMENT BY valor_de_incremento));

-- Permitir ingreso manual sin NULL en la secuencia
ALTER TABLE nombre_tabla MODIFY (campo TIPODEDATO_ENTERO GENERATED BY DEFAULT AS IDENTITY (START WITH valor_inicial));

-- Permitir ingreso manual con NULL en la secuencia
ALTER TABLE nombre_tabla MODIFY (campo TIPODEDATO_ENTERO GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH valor_inicial));

-- Negar ingreso manual en la secuencia
ALTER TABLE nombre_tabla MODIFY (campo TIPODEDATO_ENTERO GENERATED ALWAYS AS IDENTITY (START WITH valor_inicial));

-- Borrar secuencia
ALTER TABLE nombre_tabla MODIFY campo DROP IDENTITY;